---
- name: check if the device has partition layout
  become: true
  become_user: root
  command: sfdisk -d {{docker_provision_thinpool_device_name}}
  register: partition_layout

- name: run tasks to provision thinpool
  when: partition_layout.stdout == ""
  include: provision.yml

- name: Check that docker is installed
  stat:
    path: /usr/bin/docker
  register: stat_result

- name: Changing docker backend to devicmapper
  when: stat_result.stat.exists == True
  include: devicmapper.yml
